### Crear un nuevo usuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "estefani",
  "correo": "estefani@mail.com"
}

###

### Ver todos los usuarios
GET http://localhost:3000/api/usuarios

###

### Actualizar usuario con ID 1
PUT http://localhost:3000/api/usuarios/2
Content-Type: application/json

{
  "nombre": "Anabel",
  "correo": "anabel@mail.com"
}


###

### Eliminar usuario con ID 1
DELETE http://localhost:3000/api/usuarios/1

